services:
  server:
    build:
      context: .
      target: server-base
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./public:/app/public
    depends_on:
    - app
    networks:
    - default
    ports:
      - "127.0.0.1:9901:80"

  app:
    build:
      context: .
      target: php-builder
    env_file:
    - .env
    - .env.dev
    volumes:
    - .:/app:z
    networks:
    - default
